# serverless.yml

service: onillambda

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: lambda_entrypoint.application
    packRequirements: false
  pythonRequirements:
    slim: true
    dockerizePip: non-linux
    pythonBin: python

package:
  exclude:
  - .venv/**
  - .idea/**
  - .git/**
  - .ebextensions/**
  - .elasticbeanstalk/**
  - .vscode/**

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    GSHEETS_SHEET: ${file(./secrets.yml):GSHEETS_SHEET}
    REDIS_HOST: ${file(./secrets.yml):REDIS_HOST}
    GSPREAD_CREDENTIALS: ${file(./secrets.yml):GSPREAD_CREDENTIALS}
    REDIS_PWD: ${file(./secrets.yml):REDIS_PWD}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'