# serverless.yml

service: onillambda-apiv2

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline

custom:
  wsgi:
    app: api.app
    packRequirements: false
  pythonRequirements:
    slim: true
    dockerizePip: non-linux
    pythonBin: python
  secrets: ${file(secrets.json)}


package:
  exclude:
  - .venv/**
  - .idea/**
  - .git/**
  - .ebextensions/**
  - .elasticbeanstalk/**
  - .vscode/**
  - app/**

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY api
      - http: 'ANY api/{proxy+}'

